### ISSUE TITLE
Clients/show

### ISSUE THREAD

**Issue by natatkinson** [natatkinson/PancakeAppPHPWrapper#1]
500 Error on PancakeApp API on api_1/clients/show?id=1&X-API-KEY={api_key}
https://github.com/natatkinson/PancakeAppPHPWrapper/blob/master/pancakeapp.php#L77

**Comment by joelkallman** [comment]
I don't know if you're issue is related to mine, but it may be the client #1 doesn't exist. Request all clients and look at the ids to see if that exists.

I reported my issue here:
http://diner.pancakeapp.com/discussion/1186/api-bug-when-client-doesnt-exist-for-single-client-request-clientsshow#latest

Yours may be related

**Comment by natatkinson** [comment]
I don't have permission to view that link to diner.pancakeapp. But yeah, I checked and definitely have a client #1.

Thanks so much for your responses!
